#!/usr/bin/env python3
"""Build supabase/seed_questions.sql from content/assessments/question-bank.json.

Usage:  python scripts/build_question_seed.py
Then:   supabase db reset   (runs migrations + seed.sql + seed_questions.sql)
"""
import json, pathlib

root = pathlib.Path(__file__).resolve().parents[1]
bank = json.loads((root / "content/assessments/question-bank.json").read_text())

def q(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"

rows = []
for code, items in bank.items():
    if code.startswith("_"):
        continue
    for it in items:
        rows.append(
            "((select id from assessments where code={c}),(select id from modules where code={m}),"
            "{stem},{opts}::jsonb,{ans},{exp})".format(
                c=q(code), m=q(it["module"]), stem=q(it["stem"]),
                opts=q(json.dumps(it["options"], ensure_ascii=False)),
                ans=int(it["answer"]), exp=q(it.get("explanation", "")))
        )

sql = ("-- generated by scripts/build_question_seed.py — do not edit by hand\n"
       "insert into questions(assessment_id, module_id, stem, options, answer_idx, explanation) values\n"
       + ",\n".join(rows) + ";\n")
out = root / "supabase/seed_questions.sql"
out.write_text(sql, encoding="utf-8")
print(f"wrote {len(rows)} questions → {out.relative_to(root)}")
